services:
  backend-service:
    build:
      context: ./videogames-backend
      dockerfile: ./Dockerfile
    expose:
      - "8080"
    env_file:
      - ./videogames-backend/.env
    networks:
      - appnet

  frontend:
    build:
      context: ./videogames-frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=/api
    depends_on:
      - backend-service
    networks:
      - appnet

networks:
  appnet:
    driver: bridge